export const extractFormat = [
  {
    imgNum: 1,
    breeder: "MKX",
    thc: "THC: 87.75%",
    cdb: "CBD: 0.17%",
    type: "Hybrid",
    price: 20,
  },
  {
    imgNum: 2,
    breeder: "MKX",
    thc: "THC: 91.08%",
    cdb: "CBD: 0.06%",
    type: "Sativa",
    price: 20,
  },
  {
    imgNum: 3,
    breeder: "Motor City Cannacarts",
    thc: "THC: 83.46%",
    cdb: "CBD: 0.56%",
    type: "Hybrid",
    price: 15,
  },
  {
    imgNum: 8,
    breeder: "Kola Farms",
    thc: "THC: 91.08%",
    type: "Indica",
    cdb: "",
    price: 30,
  },
  {
    imgNum: 4,
    breeder: "Kola Farms",
    thc: "THC: 90.41%",
    type: "Sativa",
    cdb: "0.06%",
    price: 30,
  },

  // 5
  {
    imgNum: 5,
    breeder: "Bossy",
    thc: "THC: 83.41%",
    cdb: "",
    type: "Indica",
    price: 15,
  },
  {
    imgNum: 5,
    breeder: "Bossy",
    thc: "THC: 89.41%",
    type: "Indica",
    cdb: "",
    price: 20,
  },
  {
    imgNum: 6,
    breeder: "Kola Farms",
    thc: "THC: 81.08%",
    type: "Hybrid",
    cdb: "",
    price: 15,
  },
  {
    imgNum: 1,
    breeder: "MKX",
    thc: "THC: 91.08%",
    type: "Indica",
    cdb: "",
    price: 20,
  },
  {
    imgNum: 9,
    breeder: "Five Star Extracts",
    thc: "THC: 88.08%",
    type: "Hybrid",
    cdb: "",
    price: 30,
  },

  // 5
  {
    imgNum: 10,
    breeder: "Society",
    thc: "THC: 85.41%",
    cdb: "0.06%",
    type: "Sativa",
    price: 15,
  },
  {
    imgNum: 9,
    breeder: "Five Star Extracts",
    thc: "THC: 93.08%",
    type: "Indica",
    cdb: "",
    price: 30,
  },
  {
    imgNum: 6,
    breeder: "Kola Farms",
    thc: "THC: 90.08%",
    type: "Indica",
    cdb: "",
    price: 30,
  },
  {
    imgNum: 5,
    breeder: "Bossy",
    thc: "THC: 91.08%",
    type: "Hybrid",
    cdb: "",
    price: 20,
  },
  {
    imgNum: 10,
    breeder: "Five Start Extracts",
    thc: "THC: 85.08%",
    type: "Hybrid",
    cdb: "",
    price: 20,
  },
];
